version: "3.9"

services:
  rag-app:
    build: .
    image: flavorflav/rag-app:latest
    container_name: rag-app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu, compute, utility ]
    volumes:
      - ./config/rag_config.yml:/app/config/rag_config.yml:ro
      - ollama_models:/root/.ollama
    ports:
      - "${RAG_API_PORT:-8000}:8000"
    depends_on:
      rag-qdrant:
        condition: service_started
      rag-cache:
          condition: service_healthy
    environment:
      QDRANT_HOST: rag-qdrant
      QDRANT_PORT: ${QDRANT_PORT:-6333}
      RAG_CONFIG_PATH: /app/config/rag_config.yml
      REDIS_HOST: rag-cache
      REDIS_PORT: ${REDIS_PORT:-6379}
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      OLLAMA_MODELS: gemma2:2b-instruct-q4_K_M #Default model to download
    env_file:
      - .env
    command: ["python", "-m", "main_api"]
    restart: unless-stopped

  rag-indexer:
    image: flavorflav/rag-app:latest
    container_name: rag-indexer
    entrypoint: [""]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu, compute, utility ]
    depends_on:
      rag-qdrant:
        condition: service_started
      rag-cache:
          condition: service_healthy
    volumes:
      - ./config/rag_config.yml:/app/config/rag_config.yml:ro
      - ollama_models:/root/.ollama
    env_file:
      - .env
    environment:
      RAG_CONFIG_PATH: /app/config/rag_config.yml
      QDRANT_HOST: rag-qdrant
      QDRANT_PORT: ${QDRANT_PORT:-6333}
      REDIS_HOST: rag-cache
      REDIS_PORT: ${REDIS_PORT:-6379}
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      OVERRRIDE_INDEXING: ${OVERRRIDE_INDEXING:-false}
    command: ["python", "-m", "main_indexor"]
    restart: unless-stopped

  rag-qdrant:
    image: qdrant/qdrant:latest
    container_name: rag-qdrant
    env_file:
      - .env
    ports:
      - "${QDRANT_PORT:-6333}:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped

  rag-cache:
    image: redis:7-alpine
    container_name: rag-cache
    env_file:
      - .env
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  qdrant_storage:
  redis_data:
  ollama_models: