sources:
  - name: "Confluence Docs Sage"
    type: "confluence"
    base_url: "https://confluence.sage.com"
    root_ids: ["583415205", "401175554"]
    api_token: "${CONFLUENCE_TOKEN}"
    sync_interval: "12h"
